### ISSUE TITLE
Official support? Support for iobroker? 

### ISSUE THREAD

**Issue by baeriwiliwonka** [Flo-R1der/ambientika-smart_4_home-assistant#3]
Since I had no other chance to get in contact with you I opened this ticket to request support for creating an iobroker adapter for Südwind ventilation systems.

Another question I wanted to ask is if the development for HomeAssistant integration was supported directly and officially from Südwind.
According to a chat with them it is and they officially refer to your project.
For me it sounds a bit weired, since you describe you did reverse engineering and I expect that this is not needed, when it is officially supported by the manufacturer?!

So maybe you can bring a bit more light in the dark.
According to them there is also a plan for iobroker integration but the answers are very inconcrete.

Is there a possibility to get directly in contact with you? (E-Mail? Discord?)

Thanks in advance!

**Comment by Flo-R1der** [comment]
Hi baeriwiliwonka,

thanks four your message. Unfortunately I have no idea how iobroker works and what would be necessary to make the device work with iobroker.

It is very interesting, that Südwind is referring to me, since I'm not in any contract with them (beside buying devices from them as a normal customer). I know they were in contact with other guys who where also interested in an official and - more important - local Integration. Here I talked to others, that followed two approaches:
- intercepting the commands on the board (I wouldn't do this, to not damage the device and loosing warranty)
- intercepting the device network connection (I would recommend this, since you're not loosing warranty and it's more accessible to persons without deeper technical knowledge and soldering skills)

So to me there is no **official** way to integrate these devices in to any smart home system. I found out in some mails earlier this year that there is a plan for a smart-home Plattform (maybe MQTT?), but without any time-schedule. I also heard that the technical/electrical/IT stuff is done by an Südwind supplier which may lead to the slow-motion development and inconcrete answers.

But: I also had a contact with a developer, that had successfully made the onboarding process via BLE and was binding the device to a local "cloud server" (NodeJS app as POC in Docker) which exposes an MQTT-Device. He is currently writing the documentation and is planning to publish his findings on GitHub "in the near future". I think this can then also be interesting for you, as I assume iobroker should also support MQTT.

If you want to contact me via mail, you can use: "findigutt-github at yahoo.com"
 
<br>
Best Regards,
Florian

**Comment by Flo-R1der** [comment]
Hi baeriwiliwonka,

I did a new search on GitHub and found this: [ambientika](https://github.com/ambientika) / [HomeAssistant-integration-for-Ambientika](https://github.com/ambientika/HomeAssistant-integration-for-Ambientika)  
this looks more official to me. Maybe that's what the officials had in mind when they referred to GitHub.

**Comment by Flo-R1der** [comment]
Hi @yazend 

unfortunately Packages are provided "as-is" without any translation capabilities. 

You can easily change your entities name from the Home Assistant UI. The values of the entities are coming directly from the REST-API and if you want them to be translated, you can try to use the replace-filter:
`| relpace('from', 'to')` I believe 

I would not recommend to do renaming on the input_select options, as these values are directly sent to the REST-API with the Change-Mode Command. Otherwise you also need to do all the replace stuff when sending the change mode command...

Best Regards, Florian
