### ISSUE TITLE
Missing "Buy me a coffee"

### ISSUE THREAD

**Issue by TheACF** [Flo-R1der/ambientika-smart_4_home-assistant#4]
Hi,

I want to thank you so much for your work. This is the first and only easy to use working integration for any ventilation system. I think you should do more advertising for this because so lot people need this (i red 100000 of forums the last few month). It is simple and just working, also it is easy to use. And it is also working with more devices (master/slave) within one zone. Great job!!!

The only thing is, i cant thank you with more then an issue entry on github....maybe you give a chance for that with "Buy me a coffee" button or something.

Thx and kind regards Andreas

**Comment by Flo-R1der** [comment]
Hi [TheACF](https://github.com/TheACF),

I'm glad you are happy with this package. I find positive feedback or ideas for improvement is more valuable for me than a coffee. But if you want to 'Buy me a coffee', feel free to use this [Link](https://ko-fi.com/flor1der).

I don't do advertising, since i would be happier with an integration, not a package or any MQTT approach that displays a proper device and has better possibilities than this yaml code. Btw. have you tried the official [HomeAssistant-integration-for-Ambientika](https://github.com/ambientika/HomeAssistant-integration-for-Ambientika)? This repo was made public after I released my stuff. Maybe this is also a possible solution?

Best Regards,
Florian

**Comment by Flo-R1der** [comment]
First: Thank you for your donation :pray:

I'm closing this now, since Ko-fi Link is now in the Repo.
